name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "port-scanner" ]  # Trigger on pushes to port-scanner branch
  pull_request:
    branches: [ "main" ]          # Trigger on PRs to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for GHCR push
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GHCR
      run: |
        echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t portscanner .
        echo "IMAGE=portscanner" >> $GITHUB_ENV

    - name: Run tests
      run: |
        docker run --rm $IMAGE python -m pytest tests/ || echo "Tests failed but continuing"

    - name: Push to GHCR
      run: |
        docker tag $IMAGE ghcr.io/${{ github.repository_owner }}/portscanner:latest
        docker push ghcr.io/${{ github.repository_owner }}/portscanner:latest
