name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "port-scanner" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}  # Explicitly set as env var
      run: |
        echo "$GHCR_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/portscanner:latest .
        echo "IMAGE=ghcr.io/${{ github.repository_owner }}/portscanner:latest" >> $GITHUB_ENV

    - name: Run tests
      run: |
        docker run --rm $IMAGE python -m pytest tests/ || echo "Tests failed but continuing"

    - name: Push to GHCR
      run: docker push $IMAGE
