name: Terraform CI/CD

on:
  push:
    branches: [terraform-deploy]

env:
  STORAGE_ACCOUNT_NAME: "tfstate${{ vars.UNIQUE_SUFFIX }}"
  RESOURCE_GROUP: "tfstate-rg"
  CONTAINER_NAME: "tfstate"

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./terraform
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login (OIDC)
      uses: azure/login@v1
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Ensure Storage Account Exists
      run: |
        # Check if storage account exists
        if ! az storage account show \
          --name $STORAGE_ACCOUNT_NAME \
          --resource-group $RESOURCE_GROUP &>/dev/null; then
          
          echo "Creating storage account..."
          az storage account create \
            --name $STORAGE_ACCOUNT_NAME \
            --resource-group $RESOURCE_GROUP \
            --sku Standard_LRS \
            --kind StorageV2 \
            --allow-blob-public-access false
        fi

        # Ensure container exists
        az storage container create \
          --name $CONTAINER_NAME \
          --account-name $STORAGE_ACCOUNT_NAME \
          --auth-mode login \
          --fail-on-exist || true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -backend-config="key=prod.tfstate"

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
