name: Terraform CI/CD

on:
  push:
    branches: [terraform-deploy]

permissions:
  id-token: write  # Critical for OIDC
  contents: read

env:
  ARM_USE_OIDC: true  # Forces Terraform to use OIDC
  ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}  # Using VARIABLES not secrets
  ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    # OIDC Login
    - uses: azure/login@v1
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}  # From variables
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - uses: hashicorp/setup-terraform@v3

    - run: terraform init
    - run: terraform validate
    - run: terraform plan -out=tfplan
    - run: terraform apply -auto-approve tfplan
